#spring.datasource.url=jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:p6spy:mysql://chxt.club:3306/test?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  rabbitmq:
    port: 5672
    host: localhost
    username: admin
    password: admin

log:
  name: demo
  path: /Users/chenxintong/Downloads/
server:
  port: 8888
  servlet:
    context-path: /demo
swagger:
  enable: true
test: false
ftp:
  host: 192.168.3.127
  port: 21
  username:
  password:
  filepath:
flag: prod