#spring.datasource.url=jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring:
  datasource:
    username: scott
    password: 123
#    url: jdbc:p6spy:mysql://chxt.club:3306/test?characterEncoding=utf-8&useSSL=false
    url: jdbc:p6spy:oracle:thin:@127.0.0.1:1521:orcl
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  rabbitmq:
    port: 5672
    host: localhost
    username: admin
    password: admin

log:
  name: demo
  path: /Users/chenxintong/Downloads/
server:
  port: 8888
  servlet:
    context-path: /demo
swagger:
  enable: true
test: false
ftp:
  host: 192.168.3.127
  port: 21
  username:
  password:
  filepath:
flag: dev

##ftp
##ftp地址-ftp请求。ftp://192.168.3.127:22
#  ftp.host=192.168.3.127
#  #ftp端口号
#  ftp.port=22
#  #ftp请求的用户名
#  ftp.username=ftp2
#  #ftp请求的密码
#  ftp.password=123456
#  #ftp请求读取写入的文件路径
#  ftp.filepath=/
#  #http请求路径。http://192.168.3.127:82
#  ftp.web.host=192.168.3.127
#  ftp.web.port=82
